# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171009_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitingBodiesAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aged_diam_cm', models.FloatField(null=True)),
                ('aged_count', models.PositiveIntegerField()),
                ('buttons_diam_cm', models.FloatField(null=True)),
                ('buttons_count', models.PositiveIntegerField()),
                ('decomposing_diam_cm', models.FloatField(null=True)),
                ('decomposing_count', models.PositiveIntegerField()),
                ('emergents_diam_cm', models.FloatField(null=True)),
                ('emergents_count', models.PositiveIntegerField()),
                ('mature_diam_cm', models.FloatField(null=True)),
                ('mature_count', models.PositiveIntegerField()),
                ('young_diam_cm', models.FloatField(null=True)),
                ('young_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FungalAssociationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FungusApparentSubstrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FungusDetails',
            fields=[
                ('taxondetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TaxonDetails')),
                ('visible_mycelium', models.NullBooleanField(default=False)),
                ('areal_extent', models.TextField(blank=True, default='', null=True)),
                ('mycelium_description', models.TextField(blank=True, default='', null=True)),
                ('apparent_substrate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FungusApparentSubstrate')),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Aspect')),
                ('canopy_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CanopyCover')),
                ('disturbance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DisturbanceType')),
                ('earthworm_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EarthwormEvidence')),
                ('fruiting_bodies_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FruitingBodiesAge')),
                ('landscape_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LandscapePosition')),
            ],
            bases=('core.taxondetails',),
        ),
        migrations.CreateModel(
            name='MushroomGrowthForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushroomOdor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushroomVerticalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservedAssociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ants_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ants', to='core.FungalAssociationType')),
                ('badger_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badger', to='core.FungalAssociationType')),
                ('beetles_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beetles', to='core.FungalAssociationType')),
                ('chipmunk_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chipmunk', to='core.FungalAssociationType')),
                ('deer_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deer', to='core.FungalAssociationType')),
                ('easter_gray_squirrel_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='easter_gray_squirrel', to='core.FungalAssociationType')),
                ('gnat_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gnat', to='core.FungalAssociationType')),
                ('other_small_rodent_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_small_rodent', to='core.FungalAssociationType')),
                ('skunk_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skunk', to='core.FungalAssociationType')),
                ('slug_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug', to='core.FungalAssociationType')),
                ('snail_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snail', to='core.FungalAssociationType')),
                ('snow_flea_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snow_flea', to='core.FungalAssociationType')),
                ('termite_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termite', to='core.FungalAssociationType')),
                ('turtle_association_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turtle', to='core.FungalAssociationType')),
            ],
        ),
        migrations.AddField(
            model_name='fungusdetails',
            name='mushroom_growth_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MushroomGrowthForm'),
        ),
        migrations.AddField(
            model_name='fungusdetails',
            name='mushroom_odor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MushroomOdor'),
        ),
        migrations.AddField(
            model_name='fungusdetails',
            name='mushroom_vertical_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MushroomVerticalLocation'),
        ),
        migrations.AddField(
            model_name='fungusdetails',
            name='other_observed_associations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ObservedAssociations'),
        ),
        migrations.AddField(
            model_name='fungusdetails',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Slope'),
        ),
    ]
